
package com.compomics.coss.view;

import com.compomics.coss.controller.MainFrameController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import uk.ac.ebi.pride.tools.jmzreader.JMzReaderException;

/**
 *
 * @author Genet
 */
public class MainFrame extends javax.swing.JFrame {

    MainFrameController control;
    /**
     * Creates new form MainFrame
     */
    public MainFrame( MainFrameController controler) {
        this.control = controler;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spltBaseSlitpanel = new javax.swing.JSplitPane();
        spltUppersplitpanel = new javax.swing.JSplitPane();
        jSplitPane4 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNumPeaks = new javax.swing.JTextField();
        txtScanNum = new javax.swing.JTextField();
        spnSpectrum = new javax.swing.JSpinner();
        txtRetentionTime = new javax.swing.JTextField();
        txtMaxMZ = new javax.swing.JTextField();
        txtMinMZ = new javax.swing.JTextField();
        txtTotalSpec = new javax.swing.JTextField();
        pnlQuerySpecViz = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        spltupperleftsplitpael = new javax.swing.JSplitPane();
        jPanel8 = new javax.swing.JPanel();
        btnStartSearch = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnConfigSecReader = new javax.swing.JButton();
        prgProgressBart = new javax.swing.JProgressBar();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        cmbScoringfunction = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtlibspec = new javax.swing.JTextField();
        btnLibSpec = new javax.swing.JButton();
        btnQuerySpec = new javax.swing.JButton();
        txtprecTolerance = new javax.swing.JTextField();
        txtfragTolerance = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        chkremoveprec = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtfilterwindow = new javax.swing.JTextField();
        cmbTransformation = new javax.swing.JComboBox<>();
        chkTransform = new javax.swing.JCheckBox();
        btnsavesettings = new javax.swing.JButton();
        btnloadsettings = new javax.swing.JButton();
        btnclearsettings = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtqueryspec = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbprectolerance = new javax.swing.JComboBox<>();
        cmbfragmentTolerance = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane6 = new javax.swing.JSplitPane();
        jSplitPane7 = new javax.swing.JSplitPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblQuery = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblbestmatch = new javax.swing.JTable();
        pnlResultSpecViz = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtlog = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnusave = new javax.swing.JMenuItem();
        mnuimport = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuxlsx = new javax.swing.JMenuItem();
        mnucsv = new javax.swing.JMenuItem();
        mnutsv = new javax.swing.JMenuItem();
        mnuexit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mnureverseseq = new javax.swing.JMenuItem();
        mnurandomseq = new javax.swing.JMenuItem();
        mnufixedmz = new javax.swing.JMenuItem();
        mnurandommz = new javax.swing.JMenuItem();
        mnuprecursorswap = new javax.swing.JMenuItem();
        mnuannotate = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1231, 937));
        setResizable(false);

        spltBaseSlitpanel.setDividerLocation(550);
        spltBaseSlitpanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        spltBaseSlitpanel.setResizeWeight(0.7);
        spltBaseSlitpanel.setFocusTraversalPolicyProvider(true);

        spltUppersplitpanel.setDividerLocation(460);
        spltUppersplitpanel.setResizeWeight(0.5);

        jSplitPane4.setDividerLocation(200);
        jSplitPane4.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Query spectra information"));

        jLabel8.setText("No. Peaks");

        jLabel9.setText("Scan Num.");

        jLabel10.setText("Spectrum");
        jLabel10.setToolTipText("");

        jLabel11.setText("Retention time");

        jLabel12.setText("Maximum MZ");

        jLabel13.setText("Minimum MZ");

        txtNumPeaks.setEditable(false);
        txtNumPeaks.setText("0");

        txtScanNum.setEditable(false);
        txtScanNum.setText("0");

        spnSpectrum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnSpectrumStateChanged(evt);
            }
        });

        txtRetentionTime.setEditable(false);
        txtRetentionTime.setText("0");

        txtMaxMZ.setEditable(false);
        txtMaxMZ.setText("0");

        txtMinMZ.setEditable(false);
        txtMinMZ.setText("0");

        txtTotalSpec.setText("/0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtScanNum, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(txtNumPeaks))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRetentionTime, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(txtMaxMZ)
                            .addComponent(txtMinMZ))
                        .addGap(129, 129, 129))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnSpectrum, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalSpec, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(txtNumPeaks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRetentionTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtScanNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtMaxMZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtMinMZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(spnSpectrum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalSpec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane4.setTopComponent(jPanel3);

        javax.swing.GroupLayout pnlQuerySpecVizLayout = new javax.swing.GroupLayout(pnlQuerySpecViz);
        pnlQuerySpecViz.setLayout(pnlQuerySpecVizLayout);
        pnlQuerySpecVizLayout.setHorizontalGroup(
            pnlQuerySpecVizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        pnlQuerySpecVizLayout.setVerticalGroup(
            pnlQuerySpecVizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jSplitPane4.setRightComponent(pnlQuerySpecViz);

        spltUppersplitpanel.setRightComponent(jSplitPane4);

        spltupperleftsplitpael.setDividerLocation(410);
        spltupperleftsplitpael.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        spltupperleftsplitpael.setResizeWeight(0.9);
        spltupperleftsplitpael.setToolTipText("");

        btnStartSearch.setText("Start searching");
        btnStartSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartSearchActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.setActionCommand("");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnConfigSecReader.setText("Config spec reader");
        btnConfigSecReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigSecReaderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prgProgressBart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnConfigSecReader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStartSearch)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfigSecReader)
                    .addComponent(btnStartSearch)
                    .addComponent(btnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prgProgressBart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        spltupperleftsplitpael.setRightComponent(jPanel8);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Scoring functions"));

        cmbScoringfunction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MSROBIN", "Cosine similarity", "MSE" }));

        jLabel7.setText("Scoring function");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(cmbScoringfunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbScoringfunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("User Input"));

        txtlibspec.setText("C:/");
        txtlibspec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlibspecActionPerformed(evt);
            }
        });

        btnLibSpec.setText("...");
        btnLibSpec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibSpecActionPerformed(evt);
            }
        });

        btnQuerySpec.setText("...");
        btnQuerySpec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuerySpecActionPerformed(evt);
            }
        });

        txtprecTolerance.setText("10");

        txtfragTolerance.setText("0.05");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfragTolerance, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecTolerance, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(txtlibspec, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLibSpec, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuerySpec)
                .addGap(23, 23, 23))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQuerySpec, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlibspec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLibSpec, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(txtprecTolerance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtfragTolerance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("User Input"));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Preprocessing options"));

        chkremoveprec.setText("Remove precursor");

        jLabel5.setText("Filter windowSize");

        txtfilterwindow.setText("100");

        cmbTransformation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Log2", "Linear", "SquareRoot", " " }));
        cmbTransformation.setEnabled(false);

        chkTransform.setText("Transformation");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(chkTransform))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtfilterwindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(chkremoveprec))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(cmbTransformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkremoveprec)
                    .addComponent(jLabel5)
                    .addComponent(txtfilterwindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTransformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkTransform))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        btnsavesettings.setText("save setting");
        btnsavesettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavesettingsActionPerformed(evt);
            }
        });

        btnloadsettings.setText("load from file");
        btnloadsettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloadsettingsActionPerformed(evt);
            }
        });

        btnclearsettings.setText("clear settings");
        btnclearsettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearsettingsActionPerformed(evt);
            }
        });

        jLabel2.setText("Library spectra");

        jLabel3.setText("Precursor tolerance");

        jLabel4.setText("Fragment tolerance");

        txtqueryspec.setText("C:/");

        jLabel1.setText("Query spectra");

        cmbprectolerance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dalton", "PPM" }));
        cmbprectolerance.setSelectedIndex(1);

        cmbfragmentTolerance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dalton", "PPM" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbprectolerance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbfragmentTolerance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnsavesettings)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnloadsettings)
                                .addGap(18, 18, 18)
                                .addComponent(btnclearsettings))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(35, 35, 35)
                                .addComponent(txtqueryspec, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtqueryspec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbprectolerance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbfragmentTolerance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsavesettings)
                    .addComponent(btnloadsettings)
                    .addComponent(btnclearsettings))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(246, 246, 246)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(288, Short.MAX_VALUE)))
        );

        spltupperleftsplitpael.setLeftComponent(jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(spltupperleftsplitpael)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spltupperleftsplitpael, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Settings", jPanel1);

        jSplitPane6.setDividerLocation(290);
        jSplitPane6.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane6.setToolTipText("");

        jSplitPane7.setDividerLocation(150);
        jSplitPane7.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        tblQuery.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblQuery);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane7.setTopComponent(jPanel9);

        tblbestmatch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblbestmatch);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
        );

        jSplitPane7.setRightComponent(jPanel10);

        jSplitPane6.setTopComponent(jSplitPane7);

        javax.swing.GroupLayout pnlResultSpecVizLayout = new javax.swing.GroupLayout(pnlResultSpecViz);
        pnlResultSpecViz.setLayout(pnlResultSpecVizLayout);
        pnlResultSpecVizLayout.setHorizontalGroup(
            pnlResultSpecVizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );
        pnlResultSpecVizLayout.setVerticalGroup(
            pnlResultSpecVizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );

        jSplitPane6.setRightComponent(pnlResultSpecViz);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSplitPane6)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane6)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Result", jPanel2);

        spltUppersplitpanel.setLeftComponent(jTabbedPane1);
        jTabbedPane1.getAccessibleContext().setAccessibleName("tabSettingsResult");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        spltBaseSlitpanel.setTopComponent(spltUppersplitpanel);

        txtlog.setColumns(20);
        txtlog.setRows(5);
        txtlog.setText("the quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.\nthe quick brown fox jumps over the lazy dog.");
        jScrollPane1.setViewportView(txtlog);

        spltBaseSlitpanel.setBottomComponent(jScrollPane1);

        jMenu1.setText("File");

        mnusave.setText("Save ");
        mnusave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnusaveActionPerformed(evt);
            }
        });
        jMenu1.add(mnusave);

        mnuimport.setText("Import COSS result");
        mnuimport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuimportActionPerformed(evt);
            }
        });
        jMenu1.add(mnuimport);

        jMenu5.setText("Export result");

        mnuxlsx.setText("XLSX");
        mnuxlsx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuxlsxActionPerformed(evt);
            }
        });
        jMenu5.add(mnuxlsx);

        mnucsv.setText("CSV");
        mnucsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnucsvActionPerformed(evt);
            }
        });
        jMenu5.add(mnucsv);

        mnutsv.setText("TSV");
        mnutsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnutsvActionPerformed(evt);
            }
        });
        jMenu5.add(mnutsv);

        jMenu1.add(jMenu5);

        mnuexit.setText("Exit");
        mnuexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuexitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuexit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Settings");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Generate Decoy");
        jMenu3.setToolTipText("");

        mnureverseseq.setText("Revrese sequence");
        mnureverseseq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnureverseseqActionPerformed(evt);
            }
        });
        jMenu3.add(mnureverseseq);

        mnurandomseq.setText("Random sequence");
        mnurandomseq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnurandomseqActionPerformed(evt);
            }
        });
        jMenu3.add(mnurandomseq);

        mnufixedmz.setText("Fixed MZ shift");
        mnufixedmz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnufixedmzActionPerformed(evt);
            }
        });
        jMenu3.add(mnufixedmz);

        mnurandommz.setText("Random MZ shift");
        mnurandommz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnurandommzActionPerformed(evt);
            }
        });
        jMenu3.add(mnurandommz);

        mnuprecursorswap.setText("Precursor swap");
        mnuprecursorswap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuprecursorswapActionPerformed(evt);
            }
        });
        jMenu3.add(mnuprecursorswap);

        mnuannotate.setText("Annotate spectra");
        mnuannotate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuannotateActionPerformed(evt);
            }
        });
        jMenu3.add(mnuannotate);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(spltBaseSlitpanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(spltBaseSlitpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void mnuimportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuimportActionPerformed
        control.importResults();
    }//GEN-LAST:event_mnuimportActionPerformed

    private void mnuxlsxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuxlsxActionPerformed
        control.exportResults(1);
    }//GEN-LAST:event_mnuxlsxActionPerformed

    private void mnusaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnusaveActionPerformed
       control.exportResults(0);
    }//GEN-LAST:event_mnusaveActionPerformed

    private void mnucsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnucsvActionPerformed
        control.exportResults(2);
    }//GEN-LAST:event_mnucsvActionPerformed

    private void mnutsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnutsvActionPerformed
        control.exportResults(3);
    }//GEN-LAST:event_mnutsvActionPerformed

    private void mnuexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuexitActionPerformed
        int selectionOption = JOptionPane.showConfirmDialog(null,
                    "Are you sure want to exit?", "Really Closing?",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (selectionOption == JOptionPane.YES_OPTION) {
                if (control.isBussy) {
                    control.stopSearch();
                }
                System.exit(0);
            }
    }//GEN-LAST:event_mnuexitActionPerformed

    private void mnurandomseqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnurandomseqActionPerformed
        control.generateDeoy(1);
    }//GEN-LAST:event_mnurandomseqActionPerformed

    private void mnureverseseqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnureverseseqActionPerformed
        control.generateDeoy(0);
    }//GEN-LAST:event_mnureverseseqActionPerformed

    private void mnufixedmzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnufixedmzActionPerformed
        control.generateDeoy(2);
    }//GEN-LAST:event_mnufixedmzActionPerformed

    private void mnurandommzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnurandommzActionPerformed
        control.generateDeoy(3);
    }//GEN-LAST:event_mnurandommzActionPerformed

    private void mnuprecursorswapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuprecursorswapActionPerformed
        control.generateDeoy(4);
    }//GEN-LAST:event_mnuprecursorswapActionPerformed

    private void mnuannotateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuannotateActionPerformed
        control.annotateSpectrumFile(false);
    }//GEN-LAST:event_mnuannotateActionPerformed

    private void btnQuerySpecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuerySpecActionPerformed
        control.chooseTargetFile("target");
    }//GEN-LAST:event_btnQuerySpecActionPerformed

    private void btnLibSpecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibSpecActionPerformed
        control.chooseTargetFile("library");
    }//GEN-LAST:event_btnLibSpecActionPerformed

    private void btnsavesettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavesettingsActionPerformed
        control.saveSettings();
    }//GEN-LAST:event_btnsavesettingsActionPerformed

    private void btnloadsettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloadsettingsActionPerformed
        control.LoadData();
    }//GEN-LAST:event_btnloadsettingsActionPerformed

    private void clearSettings(){
        txtqueryspec.setText("");
        //cboSpectraLibrary.setSelectedIndex(0);
        cmbScoringfunction.setSelectedIndex(0);
        txtprecTolerance.setText("");
        txtfragTolerance.setText("");
    }
    private void btnclearsettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearsettingsActionPerformed
        clearSettings();
    }//GEN-LAST:event_btnclearsettingsActionPerformed

    private void btnConfigSecReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigSecReaderActionPerformed
        control.configReader();
    }//GEN-LAST:event_btnConfigSecReaderActionPerformed

    private void btnStartSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartSearchActionPerformed
        control.startSearch();
    }//GEN-LAST:event_btnStartSearchActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        control.stopSearch();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void spnSpectrumStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnSpectrumStateChanged
         try {
                    control.updateInputInfo();
                } catch (JMzReaderException ex) {
                    Logger.getLogger(TargetDB_View.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_spnSpectrumStateChanged

    private void txtlibspecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlibspecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlibspecActionPerformed

    //End of menu controls events
    
    //Setting controls events
    
    
    
    
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    public javax.swing.JButton btnConfigSecReader;
    private javax.swing.JButton btnLibSpec;
    private javax.swing.JButton btnQuerySpec;
    public javax.swing.JButton btnStartSearch;
    private javax.swing.JButton btnclearsettings;
    private javax.swing.JButton btnloadsettings;
    private javax.swing.JButton btnsavesettings;
    public javax.swing.JCheckBox chkTransform;
    public javax.swing.JCheckBox chkremoveprec;
    public javax.swing.JComboBox<String> cmbScoringfunction;
    public javax.swing.JComboBox<String> cmbTransformation;
    public javax.swing.JComboBox<String> cmbfragmentTolerance;
    public javax.swing.JComboBox<String> cmbprectolerance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JSplitPane jSplitPane6;
    private javax.swing.JSplitPane jSplitPane7;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem mnuannotate;
    private javax.swing.JMenuItem mnucsv;
    private javax.swing.JMenuItem mnuexit;
    private javax.swing.JMenuItem mnufixedmz;
    private javax.swing.JMenuItem mnuimport;
    private javax.swing.JMenuItem mnuprecursorswap;
    private javax.swing.JMenuItem mnurandommz;
    private javax.swing.JMenuItem mnurandomseq;
    private javax.swing.JMenuItem mnureverseseq;
    private javax.swing.JMenuItem mnusave;
    private javax.swing.JMenuItem mnutsv;
    private javax.swing.JMenuItem mnuxlsx;
    public javax.swing.JPanel pnlQuerySpecViz;
    public javax.swing.JPanel pnlResultSpecViz;
    public javax.swing.JProgressBar prgProgressBart;
    public javax.swing.JSplitPane spltBaseSlitpanel;
    public javax.swing.JSplitPane spltUppersplitpanel;
    public javax.swing.JSplitPane spltupperleftsplitpael;
    public javax.swing.JSpinner spnSpectrum;
    public javax.swing.JTable tblQuery;
    public javax.swing.JTable tblbestmatch;
    public javax.swing.JTextField txtMaxMZ;
    public javax.swing.JTextField txtMinMZ;
    public javax.swing.JTextField txtNumPeaks;
    public javax.swing.JTextField txtRetentionTime;
    public javax.swing.JTextField txtScanNum;
    public javax.swing.JTextField txtTotalSpec;
    public javax.swing.JTextField txtfilterwindow;
    public javax.swing.JTextField txtfragTolerance;
    public javax.swing.JTextField txtlibspec;
    public javax.swing.JTextArea txtlog;
    public javax.swing.JTextField txtprecTolerance;
    public javax.swing.JTextField txtqueryspec;
    // End of variables declaration//GEN-END:variables
}
