/*
 * Copyright 2022 compomics.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.compomics.coss.view;

import java.io.File;
import javax.swing.JFileChooser;
import com.compomics.coss.model.ConfigData;
import javax.swing.JOptionPane;

/**
 *
 * @author compomics
 */
public class Percolator_Info extends javax.swing.JFrame {

    /**
     * Creates new form Percolator_Info
     */
    ConfigData CData;
    public Percolator_Info(ConfigData cdata) {
        CData = cdata;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblPercolatorPath = new javax.swing.JLabel();
        txtPercolatorPath = new javax.swing.JTextField();
        btnSet = new javax.swing.JButton();
        btnBrowthPath = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPercolatorPath.setText("path to Percolator");

        txtPercolatorPath.setText("C:\\Percolator\\");

            btnSet.setText("Set");
            btnSet.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSetActionPerformed(evt);
                }
            });

            btnBrowthPath.setText("...");
            btnBrowthPath.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnBrowthPathActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(lblPercolatorPath)
                            .addGap(7, 7, 7)
                            .addComponent(txtPercolatorPath, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnBrowthPath))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(214, 214, 214)
                            .addComponent(btnSet, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(72, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPercolatorPath)
                        .addComponent(txtPercolatorPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBrowthPath))
                    .addGap(18, 18, 18)
                    .addComponent(btnSet)
                    .addContainerGap(26, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnBrowthPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowthPathActionPerformed
        
        JFileChooser fc = new JFileChooser();
        
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            txtPercolatorPath.setText(fc.getSelectedFile().toString());
        }
        
    }//GEN-LAST:event_btnBrowthPathActionPerformed

    private void btnSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetActionPerformed
      
        if(!new File(txtPercolatorPath.getText()).exists()){
           JOptionPane.showMessageDialog(this, "path doesn't exist");
       }
       else if(!new File(txtPercolatorPath.getText()).isDirectory()){
           JOptionPane.showMessageDialog(this, "Given path is not a directory");
       }else if(!new File(txtPercolatorPath.getText()).canRead()){
           JOptionPane.showMessageDialog(this, "no read access");
       }else{
           this.CData.setPercolatorPath(txtPercolatorPath.getText());
       }
               
    }//GEN-LAST:event_btnSetActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowthPath;
    private javax.swing.JButton btnSet;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblPercolatorPath;
    private javax.swing.JTextField txtPercolatorPath;
    // End of variables declaration//GEN-END:variables
}
